apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apicerberus.fullname" . }}-secrets
  labels:
    {{- include "apicerberus.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | default (randAlphaNum 32) | quote }}
  admin-api-key: {{ .Values.secrets.adminApiKey | default (randAlphaNum 32) | quote }}
