apiVersion: v1
kind: Service
metadata:
  name: {{ include "apicerberus.fullname" . }}
  labels:
    {{- include "apicerberus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "apicerberus.selectorLabels" . | nindent 4 }}
